kafka:
   imageExtractionMetadataTopic: ""
   Feature feature: ""
   extractedDocumentTopic: ""
   kafkaClientId: ""
   kafkaGroupId: ""
   kafkaAutoOffsetReset: ""
   int kafkaCommitIntervalMs: ""
   enableKafkaSSL: ""
   kafkaBootstrapServers: ""
   kafkaMaxRequestSize: ""
   kafkaTruststorePath: ""
   kafkaTruststoreFile: ""
   kafkaTruststorePassword: ""
   kafkaSLLProtocol: ""
   kafkaSSLCipher: ""
   kakfaPollIntervalMs: ""
   kafkaRequestTimeoutMs: ""
   lineServiceUrl: ""
   startNumberOfClasses: ""
   enableRBAC: ""
   goodnessOfFit: ""
   googleCredPath: ""
   runGVInPararell: ""